# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationformmodel',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Pahilo naam'),
        ),
    ]
