# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20171108_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationformmodel',
            name='citizenship_no',
            field=models.CharField(max_length=100, verbose_name='Citizenship Number'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='mobile_no',
            field=models.CharField(max_length=10, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='played_for',
            field=models.CharField(choices=[('Club Level', 'Club Level'), ('School Level', 'School Level'), ('Casual', 'Casual'), ('Locality', 'Locality')], default='Select', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='residential_add',
            field=models.TextField(max_length=100, verbose_name='Residential Address'),
        ),
    ]
