# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20171108_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationformmodel',
            name='batting',
            field=models.CharField(choices=[('Left Hand', 'Left Hand'), ('Right Hand', 'Right Hand')], default='Select', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='bowling_arm',
            field=models.CharField(choices=[('Left Arm', 'Left Arm'), ('Right Arm', 'Right Arm'), ('Both', 'Both')], default='Select', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='bowling_pace',
            field=models.CharField(choices=[('Med Pace', 'Med Pace'), ('Spinner', 'Spinner'), ('Fast', 'Fast')], default='Select', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='citizenship_no',
            field=models.CharField(max_length=100, verbose_name='*Citizenship Number'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='dob',
            field=models.DateField(verbose_name='*Date of Birth'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='email',
            field=models.CharField(max_length=100, verbose_name='*Email'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='*First Name'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='first_preference',
            field=models.CharField(choices=[('Batting', 'Batting'), ('Bowling', 'Bowling')], default='Select', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='health_issues',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Select', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='height',
            field=models.IntegerField(verbose_name='*Height'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='*Last Name'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='middle_name',
            field=models.CharField(max_length=50, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='mobile_no',
            field=models.CharField(max_length=10, verbose_name='*Mobile Number'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='place_of_issue',
            field=models.CharField(max_length=100, verbose_name='*Place Of Issue'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='residential_add',
            field=models.TextField(max_length=100, verbose_name='*Residential Address'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='sex',
            field=models.CharField(max_length=100, verbose_name='*Sex'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='team_captain_experience',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Select', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='weight',
            field=models.IntegerField(verbose_name='*Weight'),
        ),
        migrations.AlterField(
            model_name='registrationformmodel',
            name='wicket_keeper',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Select', max_length=20),
        ),
    ]
