# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20171109_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationformmodel',
            name='dob',
            field=models.CharField(default='2017-10-10', max_length=100, verbose_name='*Date of Birth'),
        ),
    ]
