# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20171109_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationformmodel',
            name='height',
            field=models.CharField(max_length=20, verbose_name='*Height'),
        ),
    ]
