# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20171109_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationformmodel',
            name='middle_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Middle Name'),
        ),
    ]
