# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20171109_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationformmodel',
            name='middle_name',
            field=models.CharField(default='None', max_length=50, verbose_name='Middle Name'),
        ),
    ]
